# Matrix Operations — Multiplication, Inverses, Determinants
*GT-Prep — Linear Algebra Notebook 02*

This notebook covers:
- Matrix multiplication (dot & matmul)
- Determinants and what they mean
- Matrix inverses and when they exist
- Identity matrices
- Singular matrices (non-invertible)


In [1]:
import numpy as np

A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

A, B


(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]))

In [2]:
C = A @ B  # same as np.matmul(A, B)
C


array([[19, 22],
       [43, 50]])

### Matrix Multiplication Intuition
- Multiply rows of A by columns of B  
- The result is a transformation: B applied *after* A  
- Order matters: A @ B ≠ B @ A  


In [3]:
det_A = np.linalg.det(A)
det_B = np.linalg.det(B)
det_A, det_B


(np.float64(-2.0000000000000004), np.float64(-2.000000000000005))

### What the determinant tells you
- det = 0 → matrix is *singular* (no inverse)
- det > 0 → preserves orientation
- det < 0 → flips orientation
- |det| = how much area/volume the transformation scales
